hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "402eff9a43e48027a7d44bbb5f10a6e5e1ba33360435395ef3416561f89d3a85"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "6f279379fff642377e96cfd631ab143ad6c73f8694698b55a4d32ca74def4ad0"

[[files]]
file = "config/dark-loading-screen.json"
hash = "5492c59c5ba8c74336658f03521eb713d5b1afa36ef2bf8fe8dc8ea97536513a"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "62ee2c39e787ac50e3068e2fa647b5bd3b7cc49a7a24fa5ae5d3ff0720271d87"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "3490f9bf466dc4ad0d1b1e7d4b37ee67443da6d4b1c335265aa3ae263656bb54"

[[files]]
file = "config/modmenu.json"
hash = "bd37c28662aebe4c1c543add18a43db005ff0cad8a05afb0c18889a5e8620e32"

[[files]]
file = "config/mutils/icons/icon_128x128.png"
hash = "88dc436087b7a7984b248bfef2d4d408a569a0349816a9239587bf4d124924b0"

[[files]]
file = "config/mutils/icons/icon_16x16.png"
hash = "1dc564ff233a249e4d06bf5efb23ccf275ba0c21b2b157074e8d317edc56e3af"

[[files]]
file = "config/mutils/icons/icon_256x256.png"
hash = "a3a00b204f062c95823cfefd638fd62b6546bc612269c2600fd8a6287197d110"

[[files]]
file = "config/mutils/icons/icon_32x32.png"
hash = "f892177b2d26f131e3f0d0b143ff6e5e380e1ae664c103e9a211bcb40b19390d"

[[files]]
file = "config/mutils/icons/icon_48x48.png"
hash = "0480d2babf0e6698d8e23369a6c616f6a78f2cd78df33e986d4f4661524b0f6a"

[[files]]
file = "config/mutils/icons/minecraft.icns"
hash = "34a3389ca2d7c72bf8314476ff0efa18145acffdbf45906f8e00d75e2fd4b706"

[[files]]
file = "config/mutils/icons/sherbert.aseprite"
hash = "54feeccfa91ab60a3cce90f1a46ec53e2961df2084a3a1a9d1bff50fb465fcdd"

[[files]]
file = "config/mutils/mutils.json5"
hash = "1cdc924f68f005fdeee09138a38406a726896f5eeec872d6a439778e0aac1e10"

[[files]]
file = "config/rrls.toml"
hash = "8077e4e6a405c8ebef32782a22bd18138c1322ab7c973c31932a623d958ddff3"

[[files]]
file = "config/yosbr/config/crash_assistant/config.toml"
hash = "402eff9a43e48027a7d44bbb5f10a6e5e1ba33360435395ef3416561f89d3a85"

[[files]]
file = "config/yosbr/config/dark-loading-screen.json"
hash = "5492c59c5ba8c74336658f03521eb713d5b1afa36ef2bf8fe8dc8ea97536513a"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "62ee2c39e787ac50e3068e2fa647b5bd3b7cc49a7a24fa5ae5d3ff0720271d87"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "3490f9bf466dc4ad0d1b1e7d4b37ee67443da6d4b1c335265aa3ae263656bb54"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "bd37c28662aebe4c1c543add18a43db005ff0cad8a05afb0c18889a5e8620e32"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "21635ad99e77f8e2ffa43783b00ccad02a9ab38dcb4d1a63f159d9b654f66b73"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_128x128.png"
hash = "88dc436087b7a7984b248bfef2d4d408a569a0349816a9239587bf4d124924b0"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_16x16.png"
hash = "1dc564ff233a249e4d06bf5efb23ccf275ba0c21b2b157074e8d317edc56e3af"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_256x256.png"
hash = "a3a00b204f062c95823cfefd638fd62b6546bc612269c2600fd8a6287197d110"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_32x32.png"
hash = "f892177b2d26f131e3f0d0b143ff6e5e380e1ae664c103e9a211bcb40b19390d"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_48x48.png"
hash = "0480d2babf0e6698d8e23369a6c616f6a78f2cd78df33e986d4f4661524b0f6a"

[[files]]
file = "config/yosbr/config/mutils/icons/minecraft.icns"
hash = "34a3389ca2d7c72bf8314476ff0efa18145acffdbf45906f8e00d75e2fd4b706"

[[files]]
file = "config/yosbr/config/mutils/icons/sherbert.aseprite"
hash = "54feeccfa91ab60a3cce90f1a46ec53e2961df2084a3a1a9d1bff50fb465fcdd"

[[files]]
file = "config/yosbr/config/mutils/mutils.json5"
hash = "1cdc924f68f005fdeee09138a38406a726896f5eeec872d6a439778e0aac1e10"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "8fb97650029518d042dec113e2bd7e2c6058503044b393a615043b1cefa1e8f2"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "8077e4e6a405c8ebef32782a22bd18138c1322ab7c973c31932a623d958ddff3"

[[files]]
file = "config/yosbr/config/simplehudenhanced.toml"
hash = "a74de676688deeed7c141081a79ad325a210c0a115b21fe8326e852ccdb60c37"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "85fe4f8b4fec82f36fb381d4813f986162d877a9e389727922a646194bf6a589"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "445a55bccce87dd8467f3265d1572827e8778e873e3bb70290adf0bb8a811e96"

[[files]]
file = "config/yosbr/config/tooltipscroll.json"
hash = "477f1237b20985aa54cd5157adc7b342381f507fc069399880ff5e997bcb40b3"

[[files]]
file = "config/yosbr/options.txt"
hash = "31e5c8d9e602c50ec77969c7657e31180873f621c6ef2f08363e015c89139eb4"

[[files]]
file = "mods/ModpackUtils-1.2.0+fabric.1.21.9.jar"
hash = "a408d4e2178b3796c7710158f4d84daef279d4834e59912c25922f5d2508c4f4"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "ddc96b08f1a32a08edd9b8e34257b9a37ea9b3836ae4371e26f54c4ade4fe3f1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2387b742878d652c205125f9c6385c9fae7d6a000f5603130721f4257c617875"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "ae86765993c59b09e06f972045b8f780e06c504f5210c0991a3b27b95dfacc80"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "6ef53c2c4e506e111b4bd7c1bc8804a5a7dcb2f6e3b79054575e73f6ce61ee94"
metafile = true

[[files]]
file = "mods/betteraddserver.pw.toml"
hash = "080f5f1221a2c25d466f215505459b766902621fbaa48fde2237ec719dd63ad2"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "fe9c77327c94f4a60632f3a56a7a9496f9f2f00e12ab42541eb433266a423b16"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "e02c60e3243dde712fcdc279f0ee21d31f530d58f11402c0fcb082bb429e339d"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "368b538e311c20808f1914e79813285259715b6cebee22484c53be233e1e8553"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "e38a11b1be69e9da3461582e5bc87f517ea5a0117932a5ec918612c5c4730686"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ab92afc9c86b581a10eb4e8dc52a3640deeb6d03fb662f6f53b2a21e87d74405"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b98e0aca52ce8d08ee8df7177886589511b8bca779af078a6ff4837e814bccf4"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "da925d1159906a6c993fa4be167a48ae350d77daa1950a68135bf56c4e0dbb62"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "654a1bfba4f854eeef95bb20da494e5acb4da4dc761aa8545df3d2f932f5d905"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "716b671d0b15ea17c788c571620eac83207bb2b6e8dbe0d33319838478f21efc"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "d541d1522108112346d35a6e9a3a9979d735cfc766d3ea6477c6306450c35f23"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d980c9bbc31a2fbac6070ed2c8992e2f1527839c54c4299d7a52f015775d8067"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "15c1503ad4b832881e1f33550c1f613dc414d06d138a9362ebe5eaf949100d1c"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "2a9e9968c598e234a84ccd9afc80a424d5c2ad9a37e4c85a0d36d06ddc9ebfa9"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "30897864e2380066d897fe2387db57ce3cfe1753ddb9cff4437d0888ad448fae"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "79625467f94812a83eb6fbf4e1d3884418937cc5b07fc708d05b7ab11dac16a5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "098d6976a738658ca490cc58e9fab19f06cd1a7b23199b6f1ee108d866333e22"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "c9babfbb0db58f9edfc38666af8ef4ce24fe0cd0594d3c421bb51410fb6c3fa2"
metafile = true

[[files]]
file = "mods/fastquit-3.1.1+mc1.21.9.jar"
hash = "05bdcb5193740c943489c53b0eedfd340ce1c84a9ea344df025176f8670680a6"

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "9a8c273d0efcf679d04d77ab37521c05978caff642a6c2b867d2fa2cdc8b168e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5f40e2db6037f733566c81e8f11ca3c425d738eb5a182658691f36d041b5df40"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "03aeb028187b13a940b7140789a7701febaacfb8fbad9fcbd6344c197df31f7e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ed9d0d5d4078c137900006321d35515cee46058b92df1128ea37cda3e5e1bb2b"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "fa3e6df3d222c94014c840673aa92455210d404eadceb05dd5ab3ae5a3eab6db"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6cd55df8041a48cb7f5f95ea4520f5ed59064e71ff9dab8b0e02bb922b68c9cb"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "4bf3b4e6ce176f34d70fa961fee580956567b0a79e25e3be58e020b7e9f42e32"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "4762935a3ab92c3ad07f3eb43a7bb8f9997066c9f8e9c68745f286e395f7b51e"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "978c05608ae60f7e40925d145910c124bb90db5db0ea8f8786fccd677eced4d6"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1600b1e64b297d68bafb4f5e5eeef08117645ac24922696da10c711ae587c06b"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "67d725bda8bdf2de7b3e60a42b281b31d3b3f6104cfd5d8b9a61309483343264"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "fb366bf83c141ee784428b33ff93765f87e24b6492a0e691bd52cc659ea6f960"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "cb4cce65ff8a0cf0a88fe8cb3d321f94f9d7f6a27b0a20631c9352ec0a2778ba"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "65622f61eede9486cbe0018629ff863a8853178e68f2b562f5d9a05efa35f22d"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "480117bbfe84aa4d902cd1f45053ed4df0738f12daf163d83436e5a1ac2804e2"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "bd7760e94351d6e7c19eb1f155c7a5a7fd281340b7bd556da2765e931f6c9ab5"
metafile = true

[[files]]
file = "mods/shut-up-realms.pw.toml"
hash = "1179dcf06cb5cd91ab60d719686b6d10ea7a524016930355618fb169bfcc6520"
metafile = true

[[files]]
file = "mods/simple-hud-enhanced.pw.toml"
hash = "d9bd203304b0ad45a43b2dbe1fc60b6a800f58c80d418a4cb5499969625e13ff"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "337f32c0d29c302db27f1fe8a636a2c756e1fdc7b4df265c181c0a691f7800f7"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4f57108f9e1c6281cfdaf3812e6bc2a2f16609a845c9912218ada90b1603e1b3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8c961dbadf2dde334c857d0b42a6c6452aa77a146cf80d4febf7f46e4ac2ef6"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/threadtweak-fabric-0.1.7+mc1.21.9-rc1.jar"
hash = "ecc36ab95c45e43531fd8611d70e2943a2c144cd044c71e2b3061e0e6fbca043"

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "d45fda81ba6cf8367049b6990140ed81c75193ebc9866595ee050ff464a701eb"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "8861c0827d996f379eb2ed607d39f8e1357c06737f52523ce4510e3126baedcc"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "1bb9b2e75c6934b1f18648e9b37e20abcf6a4a2547c7cdb0abe88407267e0c10"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true

[[files]]
file = "resourcepacks/aseprite-fonts.pw.toml"
hash = "3c1718a9dab1ad7176fb3746c8638c15dc6b61eb08fb857cc621516970264518"
metafile = true

[[files]]
file = "resourcepacks/rethoughted-gui.pw.toml"
hash = "9045453fb91538a11d3bf63ad9c63de2300266356f8c8d1249642b49e148d426"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
