hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "0f6f4e0da0355c82b64bec3b78ed74440010c21b4bd07ba1f0ea0046becec718"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "62ee2c39e787ac50e3068e2fa647b5bd3b7cc49a7a24fa5ae5d3ff0720271d87"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "3490f9bf466dc4ad0d1b1e7d4b37ee67443da6d4b1c335265aa3ae263656bb54"

[[files]]
file = "config/modmenu.json"
hash = "bd37c28662aebe4c1c543add18a43db005ff0cad8a05afb0c18889a5e8620e32"

[[files]]
file = "config/mutils/icons/icon_128x128.png"
hash = "88dc436087b7a7984b248bfef2d4d408a569a0349816a9239587bf4d124924b0"

[[files]]
file = "config/mutils/icons/icon_16x16.png"
hash = "1dc564ff233a249e4d06bf5efb23ccf275ba0c21b2b157074e8d317edc56e3af"

[[files]]
file = "config/mutils/icons/icon_256x256.png"
hash = "a3a00b204f062c95823cfefd638fd62b6546bc612269c2600fd8a6287197d110"

[[files]]
file = "config/mutils/icons/icon_32x32.png"
hash = "f892177b2d26f131e3f0d0b143ff6e5e380e1ae664c103e9a211bcb40b19390d"

[[files]]
file = "config/mutils/icons/icon_48x48.png"
hash = "0480d2babf0e6698d8e23369a6c616f6a78f2cd78df33e986d4f4661524b0f6a"

[[files]]
file = "config/mutils/icons/minecraft.icns"
hash = "34a3389ca2d7c72bf8314476ff0efa18145acffdbf45906f8e00d75e2fd4b706"

[[files]]
file = "config/mutils/icons/sherbert.aseprite"
hash = "54feeccfa91ab60a3cce90f1a46ec53e2961df2084a3a1a9d1bff50fb465fcdd"

[[files]]
file = "config/mutils/mutils.json5"
hash = "ef37f6b24f094b2cf0a356182e740c3126f0b5241e1301fa1ecf6a9771fc336a"

[[files]]
file = "config/rrls.toml"
hash = "8077e4e6a405c8ebef32782a22bd18138c1322ab7c973c31932a623d958ddff3"

[[files]]
file = "config/yosbr/config/crash_assistant/config.toml"
hash = "402eff9a43e48027a7d44bbb5f10a6e5e1ba33360435395ef3416561f89d3a85"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "b3107df758fb439e2e9012c5dbd5983f666e79f1b2d69417fd11b13e2d5da2e7"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "3490f9bf466dc4ad0d1b1e7d4b37ee67443da6d4b1c335265aa3ae263656bb54"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "bd37c28662aebe4c1c543add18a43db005ff0cad8a05afb0c18889a5e8620e32"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "21635ad99e77f8e2ffa43783b00ccad02a9ab38dcb4d1a63f159d9b654f66b73"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_128x128.png"
hash = "88dc436087b7a7984b248bfef2d4d408a569a0349816a9239587bf4d124924b0"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_16x16.png"
hash = "1dc564ff233a249e4d06bf5efb23ccf275ba0c21b2b157074e8d317edc56e3af"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_256x256.png"
hash = "a3a00b204f062c95823cfefd638fd62b6546bc612269c2600fd8a6287197d110"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_32x32.png"
hash = "f892177b2d26f131e3f0d0b143ff6e5e380e1ae664c103e9a211bcb40b19390d"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_48x48.png"
hash = "0480d2babf0e6698d8e23369a6c616f6a78f2cd78df33e986d4f4661524b0f6a"

[[files]]
file = "config/yosbr/config/mutils/icons/minecraft.icns"
hash = "34a3389ca2d7c72bf8314476ff0efa18145acffdbf45906f8e00d75e2fd4b706"

[[files]]
file = "config/yosbr/config/mutils/icons/sherbert.aseprite"
hash = "54feeccfa91ab60a3cce90f1a46ec53e2961df2084a3a1a9d1bff50fb465fcdd"

[[files]]
file = "config/yosbr/config/mutils/mutils.json5"
hash = "ef37f6b24f094b2cf0a356182e740c3126f0b5241e1301fa1ecf6a9771fc336a"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "669716266465dfd0aa156d82d9f418acd0253563c1bb7747230ba9963a56ee8a"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "8077e4e6a405c8ebef32782a22bd18138c1322ab7c973c31932a623d958ddff3"

[[files]]
file = "config/yosbr/config/simplehudenhanced.toml"
hash = "a74de676688deeed7c141081a79ad325a210c0a115b21fe8326e852ccdb60c37"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "85fe4f8b4fec82f36fb381d4813f986162d877a9e389727922a646194bf6a589"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "445a55bccce87dd8467f3265d1572827e8778e873e3bb70290adf0bb8a811e96"

[[files]]
file = "config/yosbr/config/tooltipscroll.json"
hash = "477f1237b20985aa54cd5157adc7b342381f507fc069399880ff5e997bcb40b3"

[[files]]
file = "config/yosbr/options.txt"
hash = "3be041270d8292266e8e274877adc7ce287d56ca3a717408e0c9e932fba830f0"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fc8ffe66dc0c7eb55cf2ce38d1ae4bf1c4cdfbfdcda2636b1cd140c851e03cc5"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a8785544fb032c24853b8ed9bb15d65c30312f1ee5f7ada3e73a0350512702a0"
metafile = true

[[files]]
file = "mods/chunks-fade-in.pw.toml"
hash = "ea0056315c63d05094d64592ed62cbd2a0f36634cd699036b31704cfad1036b3"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "7db50b8cf17104e1fb7a0b4cc6332cfed473c6294c1bd8a80b16006834ef6f60"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3a96a1e5bef30c16a8738c2a8acf54693225122424c39fa06f589a11ccc83b90"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6adf5f512651c200a320219c32a3a51c8b95e219206f64b99cb93940d51b2cfa"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "78568b988a30084520820c45d6f03de3442eca5800d77e870879200af28b5bc2"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "87dea750205910be6e5184ca4cdc3a3f2f439364435408b8e7a1036fdf3c28fc"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "dc930299b4c11cbd31712a3b91231bac4be1f34d00a464bfbe1a0674f5187d11"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e7e614a628196a9985630d6ce763c475ead83ff037a935a2b06a5536e694deb8"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "528bd88bf8a50ad8917ba081d7376cab0c0c7faeb0de63d6151442e4b66429fe"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "6225ea9413da6413cc543199774832a0f65d20fa64013dede1c418eb1a7ef269"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6dbca2c20d66b076bb4e8959ea0e26887991acf48f785aae402e066d5e3eb6ea"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "7a1d18504e615e902ed766ad9fb4898bce1009073a8674d33d59118061d9ccdf"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "737cad57d571acc5fc7c8458b61f13e7fc234ba97adc2b6e8700054f4a6b87f2"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "e542e032b9504f15f634907a7bab56f18f143da2f68621d6ffe22a9148ae2b48"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "c05ebfcd748f6cdb6babfee3af56f69ec44a8c3f8c671d4d97bc7dc27250eac9"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "480117bbfe84aa4d902cd1f45053ed4df0738f12daf163d83436e5a1ac2804e2"
metafile = true

[[files]]
file = "mods/shut-up-realms.pw.toml"
hash = "1179dcf06cb5cd91ab60d719686b6d10ea7a524016930355618fb169bfcc6520"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "382ad4f938be83c05d9ae6dc7bf24581f54173f5345c485abf3e3ff7618bb59e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f61bd9fbfa3fcc5d8267b5cbe6af08c93385752ddc6e6b74df0fbcfd5747e413"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "47c3ed0e67a03d71e1703de4e7b0fb8d04241bc84404c0fbe99f061c8eb18847"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d74d244b3524bea2326becd2ceaa27b8e231156aba33448533cd29b12ed48318"
metafile = true

[[files]]
file = "resourcepacks/Sherbert Colors.zip"
hash = "1ec5f292c352a30c93984db0674f555d8f2a2b988a83eb9937d164fb6454c4c8"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/mellow.pw.toml"
hash = "55191ceeb84776cf184dbce17983b966ab9a16b166c95664cb01fa161b980ccb"
metafile = true
