hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "0f6f4e0da0355c82b64bec3b78ed74440010c21b4bd07ba1f0ea0046becec718"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "62ee2c39e787ac50e3068e2fa647b5bd3b7cc49a7a24fa5ae5d3ff0720271d87"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "3490f9bf466dc4ad0d1b1e7d4b37ee67443da6d4b1c335265aa3ae263656bb54"

[[files]]
file = "config/modmenu.json"
hash = "bd37c28662aebe4c1c543add18a43db005ff0cad8a05afb0c18889a5e8620e32"

[[files]]
file = "config/mutils/icons/icon_128x128.png"
hash = "88dc436087b7a7984b248bfef2d4d408a569a0349816a9239587bf4d124924b0"

[[files]]
file = "config/mutils/icons/icon_16x16.png"
hash = "1dc564ff233a249e4d06bf5efb23ccf275ba0c21b2b157074e8d317edc56e3af"

[[files]]
file = "config/mutils/icons/icon_256x256.png"
hash = "a3a00b204f062c95823cfefd638fd62b6546bc612269c2600fd8a6287197d110"

[[files]]
file = "config/mutils/icons/icon_32x32.png"
hash = "f892177b2d26f131e3f0d0b143ff6e5e380e1ae664c103e9a211bcb40b19390d"

[[files]]
file = "config/mutils/icons/icon_48x48.png"
hash = "0480d2babf0e6698d8e23369a6c616f6a78f2cd78df33e986d4f4661524b0f6a"

[[files]]
file = "config/mutils/icons/minecraft.icns"
hash = "34a3389ca2d7c72bf8314476ff0efa18145acffdbf45906f8e00d75e2fd4b706"

[[files]]
file = "config/mutils/icons/sherbert.aseprite"
hash = "54feeccfa91ab60a3cce90f1a46ec53e2961df2084a3a1a9d1bff50fb465fcdd"

[[files]]
file = "config/mutils/mutils.json5"
hash = "ef37f6b24f094b2cf0a356182e740c3126f0b5241e1301fa1ecf6a9771fc336a"

[[files]]
file = "config/rrls.toml"
hash = "8077e4e6a405c8ebef32782a22bd18138c1322ab7c973c31932a623d958ddff3"

[[files]]
file = "config/yosbr/config/crash_assistant/config.toml"
hash = "402eff9a43e48027a7d44bbb5f10a6e5e1ba33360435395ef3416561f89d3a85"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "b3107df758fb439e2e9012c5dbd5983f666e79f1b2d69417fd11b13e2d5da2e7"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "3490f9bf466dc4ad0d1b1e7d4b37ee67443da6d4b1c335265aa3ae263656bb54"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "bd37c28662aebe4c1c543add18a43db005ff0cad8a05afb0c18889a5e8620e32"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "21635ad99e77f8e2ffa43783b00ccad02a9ab38dcb4d1a63f159d9b654f66b73"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_128x128.png"
hash = "88dc436087b7a7984b248bfef2d4d408a569a0349816a9239587bf4d124924b0"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_16x16.png"
hash = "1dc564ff233a249e4d06bf5efb23ccf275ba0c21b2b157074e8d317edc56e3af"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_256x256.png"
hash = "a3a00b204f062c95823cfefd638fd62b6546bc612269c2600fd8a6287197d110"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_32x32.png"
hash = "f892177b2d26f131e3f0d0b143ff6e5e380e1ae664c103e9a211bcb40b19390d"

[[files]]
file = "config/yosbr/config/mutils/icons/icon_48x48.png"
hash = "0480d2babf0e6698d8e23369a6c616f6a78f2cd78df33e986d4f4661524b0f6a"

[[files]]
file = "config/yosbr/config/mutils/icons/minecraft.icns"
hash = "34a3389ca2d7c72bf8314476ff0efa18145acffdbf45906f8e00d75e2fd4b706"

[[files]]
file = "config/yosbr/config/mutils/icons/sherbert.aseprite"
hash = "54feeccfa91ab60a3cce90f1a46ec53e2961df2084a3a1a9d1bff50fb465fcdd"

[[files]]
file = "config/yosbr/config/mutils/mutils.json5"
hash = "ef37f6b24f094b2cf0a356182e740c3126f0b5241e1301fa1ecf6a9771fc336a"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "669716266465dfd0aa156d82d9f418acd0253563c1bb7747230ba9963a56ee8a"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "8077e4e6a405c8ebef32782a22bd18138c1322ab7c973c31932a623d958ddff3"

[[files]]
file = "config/yosbr/config/simplehudenhanced.toml"
hash = "a74de676688deeed7c141081a79ad325a210c0a115b21fe8326e852ccdb60c37"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "85fe4f8b4fec82f36fb381d4813f986162d877a9e389727922a646194bf6a589"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "445a55bccce87dd8467f3265d1572827e8778e873e3bb70290adf0bb8a811e96"

[[files]]
file = "config/yosbr/config/tooltipscroll.json"
hash = "477f1237b20985aa54cd5157adc7b342381f507fc069399880ff5e997bcb40b3"

[[files]]
file = "config/yosbr/options.txt"
hash = "3be041270d8292266e8e274877adc7ce287d56ca3a717408e0c9e932fba830f0"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fc8ffe66dc0c7eb55cf2ce38d1ae4bf1c4cdfbfdcda2636b1cd140c851e03cc5"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "ac9911e6921b1230e34b784bc65cb0c49837bc0d5ad7584aef25e5c62812a8fc"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a8785544fb032c24853b8ed9bb15d65c30312f1ee5f7ada3e73a0350512702a0"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "092508af534efeb380b9551663980ab1f701d88583a63227d02cb02843335f7a"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "6ec28ebfa58cff496525c6c099d918cd90fe9fdc6765141b2ca993b4d8fd4426"
metafile = true

[[files]]
file = "mods/chunks-fade-in.pw.toml"
hash = "7f37931f28d7e9ea399c9e19ab4612cc1e0f614cc9ea192899518ed57c8e8873"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "72f3dbfcfbf16d8437d865b090c4338cf32de86f290e8e8dde5626cb301bb4c7"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "1b3666ed4b9327eb423aaf804ec881c657aefd2d6240b258eef886b641f5694a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3a96a1e5bef30c16a8738c2a8acf54693225122424c39fa06f589a11ccc83b90"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d3e263880c1393d7e8233979a19f97ff9cc40e2100d7a61495a5f7ef109ecf0e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6adf5f512651c200a320219c32a3a51c8b95e219206f64b99cb93940d51b2cfa"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "09d9bcf41357ee2baf28a26418bc1ed5d68ad7044252e976081295bde8dddb2e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cf6edd71a012b437bca4bcac93c44d1109632db31b5f638d28b58fa77cf771b5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "87dea750205910be6e5184ca4cdc3a3f2f439364435408b8e7a1036fdf3c28fc"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/graceful-packets.pw.toml"
hash = "935b33f6c11463aca36096834b70c964d2cfb8a42a55454520cd9073152ac8be"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "dc930299b4c11cbd31712a3b91231bac4be1f34d00a464bfbe1a0674f5187d11"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "442468b81b595bb843af8ca225b51dbf5389f3ddaf07c009d1d2e6bc9f8d7610"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "88a36b21d538d44aca7dd0a7e5ad8c09b1b263be3f4381e3bb22bc9f94ee7290"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7f26c8df78d02b1d63a723a3a45b838415126da5296ac67b0414e564da30a421"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "ec6cca86e9b3f9095b6b8fe66398618067cc23e5c273cfdb25dfb5263c7aeec6"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6dbca2c20d66b076bb4e8959ea0e26887991acf48f785aae402e066d5e3eb6ea"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "05e66fdfaf3f922718f38a18090c498d612160d342a7e3846fb7f666cf8bac3d"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "c1906aafc5af2f95945d31f840263f3490efe781461fbcee33df3f3a68c431b3"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "7a1d18504e615e902ed766ad9fb4898bce1009073a8674d33d59118061d9ccdf"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "10e5927ba9ddb93e40ab50990b34317069a2dc251109dbc24177eaca8b082275"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "8eb360a7056cd39f75c60123c9f4069dd607c67862fe22d1d83397f87d4e485a"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "737cad57d571acc5fc7c8458b61f13e7fc234ba97adc2b6e8700054f4a6b87f2"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "e542e032b9504f15f634907a7bab56f18f143da2f68621d6ffe22a9148ae2b48"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "c05ebfcd748f6cdb6babfee3af56f69ec44a8c3f8c671d4d97bc7dc27250eac9"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "480117bbfe84aa4d902cd1f45053ed4df0738f12daf163d83436e5a1ac2804e2"
metafile = true

[[files]]
file = "mods/shut-up-realms.pw.toml"
hash = "1179dcf06cb5cd91ab60d719686b6d10ea7a524016930355618fb169bfcc6520"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "35def5d4e453ead734edec6fe21f32f74cf5c85bcd2b253a501f45a2c4b1e3f1"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "382ad4f938be83c05d9ae6dc7bf24581f54173f5345c485abf3e3ff7618bb59e"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "248d96043d3cd40e0d73c02e649d5d55967ebc2ba10e60b58ba75bfba3476425"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f61bd9fbfa3fcc5d8267b5cbe6af08c93385752ddc6e6b74df0fbcfd5747e413"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "35abc4d5fb4ea1aa30144a8c5e3120afe740a0124513bc75172b19992428cecb"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "d23deb48fa3726706619a53f55948bad36a7f03af43d1a9cc21da2239f14b066"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "158242203ca5ed82f7c2628f0c2ec05c94a93d6102a8fd88a21aa9fe30afee76"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d74d244b3524bea2326becd2ceaa27b8e231156aba33448533cd29b12ed48318"
metafile = true

[[files]]
file = "resourcepacks/Sherbert Colors.zip"
hash = "1ec5f292c352a30c93984db0674f555d8f2a2b988a83eb9937d164fb6454c4c8"

[[files]]
file = "resourcepacks/aseprite-fonts.pw.toml"
hash = "3c1718a9dab1ad7176fb3746c8638c15dc6b61eb08fb857cc621516970264518"
metafile = true

[[files]]
file = "resourcepacks/rethoughted-gui.pw.toml"
hash = "870344f520c6a2cfe1c86e79b14187093f280f6bfbd30a9fc543fad16989b77d"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/mellow.pw.toml"
hash = "55191ceeb84776cf184dbce17983b966ab9a16b166c95664cb01fa161b980ccb"
metafile = true
