name = "Sherbert"
author = "Welsey_"
version = "4.0.0-beta1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb4476020067daf17b0a592db2b0f0c772c0ef8335f9f412b7ce4fe808e7153"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11", "1.21.10", "1.21.9", "1.21.8"]
