name = "Sherbert"
author = "Welsey_"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8e85ef15da7def04344ab79cab48d98700750e3381fc9b55476493d4f08b487"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.1", "1.21.4", "1.21.5", "1.21.8", "1.21.9"]
