name = "Sherbert"
author = "Welsey_"
version = "4.0.0-beta1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b94cfd64f882c2078ba666867d6db9b4224228e0c776afce56d400aca6af019"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11"]
