name = "Sherbert"
author = "Welsey_"
version = "3.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f525b6f84cfd38aa7edcbe025fd31a35367ef3b0c7359502fa3c0dce40a51e0e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.1", "1.21.4", "1.21.5", "1.21.8", "1.21.9"]
