name = "Sherbert"
author = "Welsey_"
version = "4.0.0-beta1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30dbac0b23bee5026521057e8e8f4b35e06c651db1ab5247e4bc540e326d251b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11"]
