name = "Sherbert"
author = "Welsey_"
version = "3.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7afeabaf0e4322682138edcdcfc39e7d8b9576e9caab29fd00b7a4e2e352e31"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.1", "1.21.4", "1.21.5", "1.21.8", "1.21.9"]
