name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packwiz
        uses: actionhippie/install-packwiz@v1

      - name: Run packwiz mr export
        run: |
          cd src
          packwiz mr export

      - name: Get Version
        id: get_version
        uses: sravinet/toml-select@v1.0.1
        with:
          file: 'src/pack.toml'
          field: 'version'

      - name: Get Changelog
        id: get_changelog
        run: |
          changelog_content=$(cat changelog.md)
          echo "changelog_content=${changelog_content}" >> $GITHUB_OUTPUT

      - name: Construct Release Name
        id: construct_name
        run: |
          release_name="Sherbert ${{ steps.get_version.outputs.value }}"
          echo "release_name=${release_name}" >> $GITHUB_OUTPUT

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: sherbert
          name: ${{ steps.construct_name.outputs.release_name }}
          version: ${{ steps.get_version.outputs.value }}S
          changelog: ${{ steps.get_changelog.outputs.changelog_content }}
          loaders: |- 
            fabric
          game-versions: |-
            ${{ steps.get_version.outputs.value }}
          files: |-
            src/${{ steps.construct_name.outputs.release_name }}.mrpack
          primary-file: ${{ steps.construct_name.outputs.release_name }}

      - name: Upload .mrpack to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ steps.construct_name.outputs.release_name }}
          body: ${{ steps.get_changelog.outputs.changelog_content }}
          files: src/*.mrpack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
