name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packwiz
        uses: actionhippie/install-packwiz@v1

      - name: Run packwiz mr export
        run: |
          cd src
          packwiz mr export

      - name: Get Version
        id: get_version
        uses: sravinet/toml-select@v1.0.1
        with:
          file: 'src/pack.toml'
          field: 'version'

      - name: Get Minecraft Version
        id: get_minecraft_version
        uses: sravinet/toml-select@v1.0.1
        with:
          file: 'src/pack.toml'
          field: 'versions.minecraft'
      
      - name: Get Changelog
        id: get_changelog
        run: |
          changelog_content=$(cat changelog.md)
          echo "changelog_content=${changelog_content}" >> $GITHUB_OUTPUT

      - name: Construct Release Name
        id: construct_name
        run: |
          release_name="Sherbert ${{ steps.get_version.outputs.value }}"
          echo "release_name=${release_name}" >> $GITHUB_OUTPUT

      - name: Determine Channel
        id: determine_channel
        run: |
          if [[ "${{ steps.construct_name.outputs.release_name }}" == *"beta"* ]]; then
            echo "output=beta" >> $GITHUB_ENV
          else
            echo "output=release" >> $GITHUB_ENV
          fi

      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          file_path: src/Sherbert-${{ steps.get_version.outputs.value }}.mrpack
          name: ${{ steps.construct_name.outputs.release_name }}
          version: ${{ steps.get_version.outputs.value }}
          changelog: ${{ steps.get_changelog.outputs.changelog_content }}
          game_versions: ${{ steps.get_minecraft_version.outputs.value }}
          release_type: ${{ steps.determine_channel.outputs.output }}
          loaders: fabric
          featured: true
          project_id: ${{ secrets.MODRINTH_PID }}

      - name: Update GitHub Release
        run: |
          TAG=${{ github.event.release.tag_name }}
          BODY=${{ steps.get_changelog.outputs.changelog_content }}
          gh release edit "$TAG" --body "$BODY"
          gh release upload "$TAG" src/Sherbert-${{ steps.get_version.outputs.value }}.mrpack --clobber

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
